import { Subscription } from './model/subscription-schema'

export type { Subscription } from './model/subscription-schema'
export { subscriptionSchema } from './model/subscription-schema'

export const subscriptions: Subscription[] = [
  {
    id: 1,
    name: 'Яндекс Плюс',
    notes: 'С подпиской идёт музыка и Кинопоиск',
    amount: 299,
    currency: 'RUB',
    service: 'yandex_plus',
    next_payment_date: 1746996000,
    is_autopay: true,
    status: 'active',
    frequency: 'month',
    notify: true,
    link: 'https://youtube.com',
  },
  {
    id: 2,
    name: 'Spotify Premium',
    notes: 'Подписка на музыку без рекламы',
    amount: 9.99,
    currency: 'USD',
    service: 'spotify',
    next_payment_date: 1715808000,
    is_autopay: true,
    status: 'active',
    frequency: 'month',
    notify: true,
    link: 'https://youtube.com',
  },
  {
    id: 3,
    name: 'SberPrime',
    notes: 'Подключена ради бонусов на доставку',
    amount: 199,
    currency: 'RUB',
    service: 'sberprime',
    next_payment_date: 1716239999,
    is_autopay: true,
    status: 'active',
    frequency: 'month',
    notify: false,
  },
  {
    id: 4,
    name: 'iCloud 50 ГБ',
    notes: 'Храню фото и документы',
    amount: 59,
    currency: 'RUB',
    service: 'icloud',
    next_payment_date: 1717008000,
    is_autopay: true,
    status: 'active',
    frequency: 'month',
    notify: true,
  },
  {
    id: 5,
    name: 'VPN Proton',
    notes: 'Для работы и безопасности',
    amount: 5,
    currency: 'USD',
    service: 'vpn',
    next_payment_date: 1717603200,
    is_autopay: false,
    status: 'active',
    frequency: 'month',
    notify: true,
    link: 'https://youtube.com',
  },
  {
    id: 6,
    name: 'Сбербанк Обслуживание карты',
    notes: 'Месячное списание за обслуживание',
    amount: 150,
    currency: 'RUB',
    service: 'bank',
    next_payment_date: 1718208000,
    is_autopay: true,
    status: 'active',
    frequency: 'month',
    notify: false,
  },
  {
    id: 7,
    name: 'Проездной на метро',
    notes: 'МЦК+метро, абонемент',
    amount: 2500,
    currency: 'RUB',
    service: 'transport',
    next_payment_date: 1718812800,
    is_autopay: false,
    status: 'active',
    frequency: 'month',
    notify: true,
  },
  {
    id: 8,
    name: 'JetBrains All Products Pack',
    notes: 'IDE для работы',
    amount: 249,
    currency: 'USD',
    service: 'software',
    next_payment_date: 1719417600,
    is_autopay: true,
    status: 'active',
    frequency: 'year',
    notify: true,
    link: 'https://youtube.com',
  },
  {
    id: 9,
    name: 'OZON Premium',
    notes: 'Бесплатная доставка и скидки',
    amount: 399,
    currency: 'RUB',
    service: 'shopping',
    next_payment_date: 1720022400,
    is_autopay: false,
    status: 'trial',
    frequency: 'month',
    notify: true,
  },
  {
    id: 10,
    name: 'Курс по TypeScript',
    notes: 'Оплата в рассрочку',
    amount: 1000,
    currency: 'RUB',
    service: 'education',
    next_payment_date: 1720627200,
    is_autopay: false,
    status: 'active',
    frequency: 'quarter',
    notify: true,
    link: 'https://youtube.com',
  },
]
