definitions:
  controller.EmailAuthRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  controller.ProfileResponse:
    properties:
      avatar_id:
        type: string
      email:
        type: string
      full_name:
        type: string
      provider:
        type: string
      user_id:
        type: integer
    type: object
  controller.VerifyEmailRequest:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    - otp
    type: object
  utils.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  utils.MessageResponse:
    properties:
      message:
        type: string
    type: object
  utils.ValidationErrorResponse:
    properties:
      fields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  description: Документация HTTP API
  title: FinanceTracker Gateway API
  version: "1.0"
paths:
  /auth/email:
    post:
      consumes:
      - application/json
      description: Отправляет одноразовый код на email
      parameters:
      - description: Email для отправки OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.EmailAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent
          schema:
            $ref: '#/definitions/utils.MessageResponse'
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/utils.ValidationErrorResponse'
        "500":
          description: Сбой при отправке
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Запросить код на email
      tags:
      - auth
  /auth/email/verify:
    post:
      consumes:
      - application/json
      description: Подтверждает OTP-код и возвращает access token
      parameters:
      - description: Email и OTP-код
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email verified or login successful
          schema:
            $ref: '#/definitions/utils.MessageResponse'
        "400":
          description: Неверные данные или код
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Внутренняя ошибка
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Подтверждение email-кода
      tags:
      - auth
  /auth/google/callback:
    get:
      description: Обрабатывает redirect от Google и выдает access token
      parameters:
      - description: Authorization Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Redirect with error
          schema:
            type: string
      summary: Callback Google OAuth
      tags:
      - auth
  /auth/google/login:
    get:
      description: Перенаправляет пользователя на Google OAuth страницу
      produces:
      - application/json
      responses:
        "307":
          description: Redirect to Google OAuth
          schema:
            type: string
      summary: Google OAuth вход
      tags:
      - auth
  /auth/yandex/callback:
    get:
      description: Обрабатывает redirect от Yandex и выдает access token
      parameters:
      - description: Authorization Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Redirect with error
          schema:
            type: string
      summary: Callback Yandex OAuth
      tags:
      - auth
  /auth/yandex/login:
    get:
      description: Перенаправляет пользователя на Yandex OAuth страницу
      produces:
      - application/json
      responses:
        "307":
          description: Redirect to Yandex OAuth
          schema:
            type: string
      summary: Yandex OAuth вход
      tags:
      - auth
  /profile/me:
    get:
      consumes:
      - application/json
      description: Возвращает информацию о профиле аутентифицированного пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ с данными профиля
          schema:
            $ref: '#/definitions/controller.ProfileResponse'
        "400":
          description: Профиль не найден
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "503":
          description: Сервис недоступен
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить профиль текущего пользователя
      tags:
      - Профиль
  /profile/update:
    put:
      consumes:
      - multipart/form-data
      description: Принимает имя и/или аватар (multipart/form-data) и обновляет профиль
      parameters:
      - description: Имя пользователя
        in: formData
        name: name
        type: string
      - description: Файл аватара (image/*)
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ с обновленным профилем
          schema:
            $ref: '#/definitions/controller.ProfileResponse'
        "400":
          description: Неверные данные или нечего обновлять
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "503":
          description: Сервис недоступен
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить профиль текущего пользователя
      tags:
      - Профиль
securityDefinitions:
  BearerAuth:
    description: Используйте формат "Bearer {token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
